
project_id = "vaabpicspdbolvutnscp"

[api]
# No overrides for API configuration

[db]
# No overrides for DB configuration

[auth]
# No overrides for Auth configuration

[storage]
# No overrides for Storage configuration

[functions.create_storage_policy]
verify_jwt = true
