// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vaabpicspdbolvutnscp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhYWJwaWNzcGRib2x2dXRuc2NwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NTI5OTIsImV4cCI6MjA2MDIyODk5Mn0.Rq3E-9JS2GJun81JCQWHXCSXzgP_EkBG7bFUx4MNAIY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);